-- Drop functions
DROP FUNCTION IF EXISTS get_all_modules;
DROP FUNCTION IF EXISTS get_modules_by_profile_id;
DROP FUNCTION IF EXISTS get_all_objects;
DROP FUNCTION IF EXISTS get_objects_by_module_id;
DROP FUNCTION IF EXISTS get_objects_by_profile_id_module_id;
DROP FUNCTION IF EXISTS get_all_methods;
DROP FUNCTION IF EXISTS get_methods_by_object_id;
DROP FUNCTION IF EXISTS get_methods_by_profile_id_object_id;
DROP FUNCTION IF EXISTS get_all_user_profiles;
DROP FUNCTION IF EXISTS get_profile_permissions_methods;
DROP FUNCTION IF EXISTS get_all_permissions;
DROP FUNCTION IF EXISTS search_user_by_username;
DROP FUNCTION IF EXISTS search_profile_by_name;
DROP FUNCTION IF EXISTS get_all_profiles;
DROP FUNCTION IF EXISTS get_all_users;
DROP FUNCTION IF EXISTS get_all_topics_name;
DROP FUNCTION IF EXISTS get_all_topics;
DROP FUNCTION IF EXISTS get_all_languages;